# Generated by Django 4.2.7 on 2026-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('generic_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('ANTIBIOTIC', 'Antibiotic'), ('ANALGESIC', 'Analgesic'), ('ANTIVIRAL', 'Antiviral'), ('CARDIOVASCULAR', 'Cardiovascular'), ('DIABETES', 'Diabetes'), ('RESPIRATORY', 'Respiratory'), ('GASTROINTESTINAL', 'Gastrointestinal'), ('EMERGENCY', 'Emergency'), ('VACCINE', 'Vaccine'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('manufacturer', models.CharField(max_length=255)),
                ('dosage_form', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('is_prescription_required', models.BooleanField(default=True)),
                ('is_essential', models.BooleanField(default=False)),
                ('is_seasonal', models.BooleanField(default=False)),
                ('peak_season_months', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicines',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='medicines_categor_fce400_idx'), models.Index(fields=['is_essential'], name='medicines_is_esse_65e1d3_idx')],
            },
        ),
    ]
